services:
  mysql:
    container_name: zincy-dev-mysql

  backend:
    container_name: zincy-dev-backend

  frontend:
    build:
      context: ./frontend

    container_name: zincy-dev-frontend
    restart: unless-stopped

    depends_on:
      - backend

    environment:
      EXPO_PUBLIC_APP_ENV: ${EXPO_PUBLIC_APP_ENV}
      EXPO_PUBLIC_API_BASE_URL: ${EXPO_PUBLIC_API_BASE_URL}

    ports:
      - "8082:80"

    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-q",
          "--spider",
          "http://127.0.0.1/health"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

    networks:
      - zincy-network

volumes:
  mysql_data:
    name: zincy_dev_mysql_data

networks:
  zincy-network:
    name: zincy_dev_network
