spring.datasource.url=jdbc:mysql://localhost:3306/zincy_corporation
spring.datasource.username=root
spring.datasource.password=Sagar@2025

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=${PORT:8081}

# =========================
# MSG91
# =========================
msg91.authkey=${MSG91_AUTH_KEY:}
msg91.templateId=${MSG91_TEMPLATE_ID:}
msg91.sender=${MSG91_SENDER:SMSIND}

# =========================
# TWILIO
# =========================
twilio.account.sid=${TWILIO_ACCOUNT_SID:}
twilio.auth.token=${TWILIO_AUTH_TOKEN:}
twilio.from-number=${TWILIO_FROM_NUMBER:}
